"""Robot models used by the FRL simulations."""

from .arm_2dof import Arm2DOF
from .arm_3dof import Arm3DOF
from .arm_4dof import Arm4DOF
from .arm_5dof import Arm5DOF
from .arm_6dof import Arm6DOF
from .dynamics import (
    Arm2DOFDynamicsConfig,
    coriolis_centrifugal_torque,
    gravity_torque,
    inverse_dynamics_torque,
    joint_acceleration,
    mass_matrix,
    viscous_friction_torque,
)
from .dynamics_3dof import (
    Arm3DOFDynamicsConfig,
    coriolis_centrifugal_torque_3dof,
    gravity_torque_3dof,
    inverse_dynamics_torque_3dof,
    joint_acceleration_3dof,
    mass_matrix_3dof,
    viscous_friction_torque_3dof,
    yaw_inertia_and_gradient,
)
from .dynamics_4dof import (
    Arm4DOFDynamicsConfig,
    coriolis_centrifugal_torque_4dof,
    gravity_torque_4dof,
    inverse_dynamics_torque_4dof,
    joint_acceleration_4dof,
    mass_matrix_4dof,
    viscous_friction_torque_4dof,
    yaw_inertia_and_gradient_4dof,
)
from .dynamics_5dof import (
    Arm5DOFDynamicsConfig,
    coriolis_centrifugal_torque_5dof,
    gravity_torque_5dof,
    inverse_dynamics_torque_5dof,
    joint_acceleration_5dof,
    mass_matrix_5dof,
    viscous_friction_torque_5dof,
    yaw_inertia_and_gradient_5dof,
)
from .dynamics_6dof import (
    Arm6DOFDynamicsConfig,
    coriolis_centrifugal_torque_6dof,
    gravity_torque_6dof,
    inverse_dynamics_torque_6dof,
    joint_acceleration_6dof,
    mass_matrix_6dof,
    viscous_friction_torque_6dof,
    yaw_inertia_and_gradient_6dof,
)
from .kinematics import (
    Arm2DOFConfig,
    clip_to_joint_limits,
    forward_kinematics,
    inverse_kinematics,
    is_reachable,
    jacobian,
    joint_positions,
    workspace_radius,
)
from .kinematics_3dof import (
    Arm3DOFConfig,
    clip_to_joint_limits_3dof,
    forward_kinematics_3dof,
    inverse_kinematics_3dof,
    is_reachable_3dof,
    jacobian_3dof,
    joint_positions_3dof,
    workspace_radius_3dof,
)
from .kinematics_4dof import (
    Arm4DOFConfig,
    clip_to_joint_limits_4dof,
    forward_kinematics_4dof,
    inverse_kinematics_4dof,
    is_reachable_4dof,
    jacobian_4dof,
    joint_positions_4dof,
    workspace_radius_4dof,
)
from .kinematics_5dof import (
    Arm5DOFConfig,
    clip_to_joint_limits_5dof,
    forward_kinematics_5dof,
    inverse_kinematics_5dof,
    is_reachable_5dof,
    jacobian_5dof,
    joint_positions_5dof,
    workspace_radius_5dof,
)
from .kinematics_6dof import (
    Arm6DOFConfig,
    clip_to_joint_limits_6dof,
    forward_kinematics_6dof,
    inverse_kinematics_6dof,
    is_reachable_6dof,
    jacobian_6dof,
    joint_positions_6dof,
    workspace_radius_6dof,
)

__all__ = [
    "Arm2DOF",
    "Arm2DOFConfig",
    "Arm2DOFDynamicsConfig",
    "Arm3DOF",
    "Arm3DOFConfig",
    "Arm3DOFDynamicsConfig",
    "Arm4DOF",
    "Arm4DOFConfig",
    "Arm4DOFDynamicsConfig",
    "Arm5DOF",
    "Arm5DOFConfig",
    "Arm5DOFDynamicsConfig",
    "Arm6DOF",
    "Arm6DOFConfig",
    "Arm6DOFDynamicsConfig",
    "clip_to_joint_limits",
    "clip_to_joint_limits_3dof",
    "clip_to_joint_limits_4dof",
    "clip_to_joint_limits_5dof",
    "clip_to_joint_limits_6dof",
    "coriolis_centrifugal_torque",
    "coriolis_centrifugal_torque_3dof",
    "coriolis_centrifugal_torque_4dof",
    "coriolis_centrifugal_torque_5dof",
    "coriolis_centrifugal_torque_6dof",
    "forward_kinematics",
    "forward_kinematics_3dof",
    "forward_kinematics_4dof",
    "forward_kinematics_5dof",
    "forward_kinematics_6dof",
    "gravity_torque",
    "gravity_torque_3dof",
    "gravity_torque_4dof",
    "gravity_torque_5dof",
    "gravity_torque_6dof",
    "inverse_dynamics_torque",
    "inverse_dynamics_torque_3dof",
    "inverse_dynamics_torque_4dof",
    "inverse_dynamics_torque_5dof",
    "inverse_dynamics_torque_6dof",
    "inverse_kinematics",
    "inverse_kinematics_3dof",
    "inverse_kinematics_4dof",
    "inverse_kinematics_5dof",
    "inverse_kinematics_6dof",
    "is_reachable",
    "is_reachable_3dof",
    "is_reachable_4dof",
    "is_reachable_5dof",
    "is_reachable_6dof",
    "jacobian",
    "jacobian_3dof",
    "jacobian_4dof",
    "jacobian_5dof",
    "jacobian_6dof",
    "joint_acceleration",
    "joint_acceleration_3dof",
    "joint_acceleration_4dof",
    "joint_acceleration_5dof",
    "joint_acceleration_6dof",
    "joint_positions",
    "joint_positions_3dof",
    "joint_positions_4dof",
    "joint_positions_5dof",
    "joint_positions_6dof",
    "mass_matrix",
    "mass_matrix_3dof",
    "mass_matrix_4dof",
    "mass_matrix_5dof",
    "mass_matrix_6dof",
    "viscous_friction_torque",
    "viscous_friction_torque_3dof",
    "viscous_friction_torque_4dof",
    "viscous_friction_torque_5dof",
    "viscous_friction_torque_6dof",
    "workspace_radius",
    "workspace_radius_3dof",
    "workspace_radius_4dof",
    "workspace_radius_5dof",
    "workspace_radius_6dof",
    "yaw_inertia_and_gradient",
    "yaw_inertia_and_gradient_4dof",
    "yaw_inertia_and_gradient_5dof",
    "yaw_inertia_and_gradient_6dof",
]
