"""Elementary dynamic-programming algorithms for finite MDPs."""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np

from .discrete_arm_mdp import DiscreteArm2DOFMDP


@dataclass(frozen=True)
class PolicyEvaluationResult:
    """Value function obtained by Bellman expectation backups."""

    value: np.ndarray
    iterations: int
    max_delta: float


@dataclass(frozen=True)
class ValueIterationResult:
    """Optimal value and greedy policy from Bellman optimality backups."""

    value: np.ndarray
    q_value: np.ndarray
    policy: np.ndarray
    iterations: int
    max_delta: float


@dataclass(frozen=True)
class Rollout:
    """Trajectory generated by a deterministic policy."""

    states: list[int]
    actions: list[int]
    rewards: list[float]
    done: bool


def discounted_return(rewards: list[float] | np.ndarray, gamma: float) -> float:
    """Return sum_t gamma^t r_t."""

    if not 0.0 <= gamma <= 1.0:
        raise ValueError("gamma must satisfy 0 <= gamma <= 1.")
    return float(sum((gamma**index) * reward for index, reward in enumerate(rewards)))


def undiscounted_return(rewards: list[float] | np.ndarray) -> float:
    """Return sum_t r_t."""

    return float(np.sum(rewards))


def _policy_action_probabilities(
    policy: np.ndarray,
    state: int,
    n_actions: int,
) -> np.ndarray:
    if policy.ndim == 1:
        probabilities = np.zeros(n_actions, dtype=float)
        probabilities[int(policy[state])] = 1.0
        return probabilities
    if policy.ndim == 2 and policy.shape[1] == n_actions:
        return policy[state]
    raise ValueError("policy must be deterministic (n_states,) or stochastic (n_states, n_actions).")


def bellman_action_values(
    mdp: DiscreteArm2DOFMDP,
    value: np.ndarray,
    gamma: float | None = None,
) -> np.ndarray:
    """Compute Q(s, a) = r + gamma V(s') for all discrete state-action pairs."""

    gamma_value = mdp.config.gamma if gamma is None else gamma
    if value.shape != (mdp.n_states,):
        raise ValueError("value has an invalid shape.")

    continuation = np.where(mdp.done, 0.0, gamma_value * value[mdp.next_states])
    return mdp.rewards + continuation


def evaluate_policy(
    mdp: DiscreteArm2DOFMDP,
    policy: np.ndarray,
    gamma: float | None = None,
    theta: float = 1e-8,
    max_iterations: int = 10_000,
) -> PolicyEvaluationResult:
    """Evaluate V_pi with the Bellman expectation equation."""

    gamma_value = mdp.config.gamma if gamma is None else gamma
    if policy.shape[0] != mdp.n_states:
        raise ValueError("policy has an invalid number of states.")
    if theta <= 0.0:
        raise ValueError("theta must be strictly positive.")
    if max_iterations <= 0:
        raise ValueError("max_iterations must be strictly positive.")

    value = np.zeros(mdp.n_states, dtype=float)
    max_delta = float("inf")

    for iteration in range(1, max_iterations + 1):
        max_delta = 0.0
        next_value = value.copy()
        for state in range(mdp.n_states):
            if mdp.is_terminal(state):
                next_value[state] = 0.0
                continue

            probabilities = _policy_action_probabilities(policy, state, mdp.n_actions)
            state_value = 0.0
            for action, probability in enumerate(probabilities):
                if probability <= 0.0:
                    continue
                next_state, reward, done = mdp.step(state, action)
                backup = reward if done else reward + gamma_value * value[next_state]
                state_value += float(probability) * backup
            next_value[state] = state_value
            max_delta = max(max_delta, abs(next_value[state] - value[state]))

        value = next_value
        if max_delta < theta:
            return PolicyEvaluationResult(value=value, iterations=iteration, max_delta=max_delta)

    return PolicyEvaluationResult(
        value=value,
        iterations=max_iterations,
        max_delta=max_delta,
    )


def value_iteration(
    mdp: DiscreteArm2DOFMDP,
    gamma: float | None = None,
    theta: float = 1e-8,
    max_iterations: int = 10_000,
) -> ValueIterationResult:
    """Solve V* with the Bellman optimality equation."""

    gamma_value = mdp.config.gamma if gamma is None else gamma
    if theta <= 0.0:
        raise ValueError("theta must be strictly positive.")
    if max_iterations <= 0:
        raise ValueError("max_iterations must be strictly positive.")

    value = np.zeros(mdp.n_states, dtype=float)
    max_delta = float("inf")

    for iteration in range(1, max_iterations + 1):
        max_delta = 0.0
        q_values = bellman_action_values(mdp, value, gamma=gamma_value)
        next_value = value.copy()
        for state in range(mdp.n_states):
            if mdp.is_terminal(state):
                next_value[state] = 0.0
                continue

            next_value[state] = float(np.max(q_values[state]))
            max_delta = max(max_delta, abs(next_value[state] - value[state]))

        value = next_value
        if max_delta < theta:
            break

    q_value = bellman_action_values(mdp, value, gamma=gamma_value)
    policy = np.argmax(q_value, axis=1)
    policy[mdp.terminal_states] = 0

    return ValueIterationResult(
        value=value,
        q_value=q_value,
        policy=policy,
        iterations=iteration,
        max_delta=max_delta,
    )


def rollout_policy(
    mdp: DiscreteArm2DOFMDP,
    policy: np.ndarray,
    start_state: int,
    max_steps: int = 200,
) -> Rollout:
    """Generate one deterministic trajectory following policy."""

    if policy.shape != (mdp.n_states,):
        raise ValueError("policy must be a deterministic action array.")
    if max_steps <= 0:
        raise ValueError("max_steps must be strictly positive.")

    state = int(start_state)
    states = [state]
    actions: list[int] = []
    rewards: list[float] = []
    done = mdp.is_terminal(state)

    for _ in range(max_steps):
        if done:
            break
        action = int(policy[state])
        next_state, reward, done = mdp.step(state, action)
        actions.append(action)
        rewards.append(reward)
        states.append(next_state)
        state = next_state

    return Rollout(states=states, actions=actions, rewards=rewards, done=done)
